sudo: required
services:
    - docker

before_install:
    - docker build -t chengadev/fibo-client-tests -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true chengadev/fibo-client-tests npm test

after_success:
    - docker build -t chengadev/fibo-client-prod ./client
    - docker build -t chengadev/fibo-nginx-prod ./nginx
    - docker build -t chengadev/fibo-server-prod ./server
    - docker build -t chengadev/fibo-worker-prod ./worker
    # Login to docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Push images to Docker hub
    - docker push chengadev/fibo-client-prod
    - docker push chengadev/fibo-nginx-prod
    - docker push chengadev/fibo-server-prod
    - docker push chengadev/fibo-worker-prod
